### ISSUE TITLE
Delete deprecated objects/fields from production

### ISSUE THREAD

**Issue by lconway-cc** [Ready-Ready/HealthySteps_Salesforce#29]
1. See Renell for a list of objects that can be depreciated in production
2. Ensure that there are no references to proposed depreciation objects
3. Depreciate objects/fields
4. Retire HSDev1220
5. Spin up new sandbox for HS dev work?

**Comment by renell-carpenter** [comment]
@KarthikRaghav here are some additional Visit fields that I believe should be deprecated. Can you please check "where used" to confirm you think they are not needed and then delete? 

FYI @CCnicolegarcia can please confirm that it is safe to delete these fields from a form perspective? I'm pretty sure at least Tier Visit Status would have been used by old versions of FA forms but shouldn't be anymore.

![image](https://user-images.githubusercontent.com/78942845/113778812-d8e7ea80-96fa-11eb-97a5-abdc6d22578c.png)

**Comment by renell-carpenter** [comment]
@KarthikRaghav 1 more field for deletion:
Tier object    xLegacy (Legacy__c)

Please let me know if you can complete this work this week so we can create a fresh Sandbox this week or early next week for the upcoming work to add the new Sites to the HealthSteps app.

FYI @CCnicolegarcia @lconway-cc

**Comment by renell-carpenter** [comment]
@KarthikRaghav Please note I learned from @CCnicolegarcia that the Form Assembly forms still leverages the:
Child object   Legacy  (Legacy__c)  
field so I took the "x" off the label and it should NOT be deleted.

**Comment by KarthikRaghav** [comment]
Hi @renell-carpenter, I have deleted the following fields from the CHS Org. I have not deleted the Legacy field from the Child object.
1. xTier Level Status - Visit
2. xPC Relation - Visit
3. xPC Race - Visit
4. xPC Gender - Visit
5. xPC Ethnicity - Visit
6. xPC Age - Visit
7. xCG Relationship - Visit
8. xLegacy - Tier

Also, as discussed I have created a new sandbox for creating and testing out the User Request and Change Request approval processes. Please let me know if we need to create another fresh sandbox to add the new sites? Thank you!

**Comment by renell-carpenter** [comment]
Great! Thanks @KarthikRaghav! We'll confirm the sandbox refresh details and timing during our 3pm call tomorrow.

**Comment by renell-carpenter** [comment]
@KarthikRaghav this can be closed now.
