### ISSUE TITLE
Tier Updates: Data patches post Release 3

### ISSUE THREAD

**Issue by KarthikRaghav** [Ready-Ready/HealthySteps_Salesforce#58]
- [ ] (Manual?) update “Legacy - Tier Entered Prior to Entry Date” on existing records for “legacy” families. I don't think we can identify which records need this so we may need to ask users to do their own updates or provide us with a list of their legacy families and maybe we can do the updates for them. Let's review/discuss.
- [ ] Review duplicate Tiers report and work with Renell/HS team to clean up: https://na96.lightning.force.com/lightning/r/Report/00O2M000009ZufAUAS/view?queryScope=userFolders
- [ ] Others?
- [ ] Delete Tier records for Incomplete Visits?: Not sure we need this or exactly how to build it - let's look at this together when you get this far along

**Comment by renell-carpenter** [comment]
@KarthikRaghav I believe this can be closed now.
